# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

State.create(name: "Alabama", abbr: "AL")
State.create(name: "Alaska", abbr: "AK")
State.create(name: "Arizona", abbr: "AZ")
State.create(name: "Arkansas", abbr: "AR")
State.create(name: "California", abbr: "CA")
State.create(name: "Conneticut", abbr: "CN")
State.create(name: "Colorado", abbr: "CO")
State.create(name: "Delaware", abbr: "DE")
State.create(name: "Florida", abbr: "FL")
State.create(name: "Georgia", abbr: "GA")
State.create(name: "Hawaii", abbr: "HI")
State.create(name: "Idaho", abbr: "ID")
State.create(name: "Illinois", abbr: "IL")
State.create(name: "Indiana", abbr: "IN")
State.create(name: "Iowa", abbr: "IA")
State.create(name: "Kansas", abbr: "KA")
State.create(name: "Kentucky", abbr: "KY")
State.create(name: "Louisiana", abbr: "LA")
State.create(name: "Massachussetts", abbr: "MA")
State.create(name: "Maine", abbr: "ME")
State.create(name: "Maryland", abbr: "MD")
State.create(name: "Michigan", abbr: "MI")
State.create(name: "Missouri", abbr: "MO")
State.create(name: "Mississippi", abbr: "MS")
State.create(name: "Minnesota", abbr: "MN")
State.create(name: "Montana", abbr: "MT")
State.create(name: "Nebraska", abbr: "NE")
State.create(name: "Nevada", abbr: "NV")
State.create(name: "New Hampshire", abbr: "NH")
State.create(name: "New Jersey", abbr: "NJ")
State.create(name: "New Mexico", abbr: "NM")
State.create(name: "New York", abbr: "NY")
State.create(name: "North Carolina", abbr: "NC")
State.create(name: "North Dakota", abbr: "ND")
State.create(name: "Oklahoma", abbr: "OK")
State.create(name: "Ohio", abbr: "OH")
State.create(name: "Oregon", abbr: "OR")
State.create(name: "Pennsylvania", abbr: "PA")
State.create(name: "Rhode Island", abbr: "RI")
State.create(name: "South Carolina", abbr: "SC")
State.create(name: "South Dakota", abbr: "SD")
State.create(name: "Tenessee", abbr: "TN")
State.create(name: "Texas", abbr: "TX",)
State.create(name: "Utah", abbr: "UT")
State.create(name: "Virginia", abbr: "VA")
State.create(name: "Vermont", abbr: "VT")
State.create(name: "Washington", abbr: "WA")
State.create(name: "Wisconsin", abbr: "WI")
State.create(name: "West virginia", abbr: "WV")
State.create(name: "Wyoming", abbr: "WY")

Category.create(name: "Sketches")
Category.create(name: "Proposals")
Category.create(name: "Photos")
Category.create(name: "Documents")
Category.create(name: "Specifications")
Category.create(name: "Request for Proposal")


